apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"port":30001,"protocol":"TCP","serviceName":"cattle-neuvector-system:neuvector-svc-controller-fed-master","allNodes":true}]
    meta.helm.sh/release-name: neuvector
    meta.helm.sh/release-namespace: cattle-neuvector-system
  labels:
    release: neuvector
  name: neuvector-svc-controller-fed-master
  namespace: cattle-neuvector-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: fed
      nodePort: 30001
      port: 11443
      protocol: TCP
      targetPort: 11443
  selector:
    app: neuvector-controller-pod
  sessionAffinity: None
  type: NodePort
