apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: service
    enable: true
    mode: monitor
  rules:
  - action: deny
    criteria:
    - name: cveHighCount
      op: '>='
      value: "10"
    - name: cveHighWithFixCount
      op: '>='
      value: "5"
    - name: cveScoreCount
      op: '>='
      sub_criteria:
      - name: count
        op: '>='
        value: "1"
      value: "9.5"
    - name: envVarSecrets
      op: =
      value: "true"
