apiVersion: v1
kind: Namespace
metadata:
  name: galileo-seven
  
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: galileo-sa
  namespace: galileo-seven
automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: galileo-seven
  name: galileo-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: galileo-rb
  namespace: galileo-seven
subjects:
- kind: ServiceAccount
  name: galileo-sa
  apiGroup: ""
roleRef:
  kind: Role 
  name: galileo-role
  apiGroup: rbac.authorization.k8s.io
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latimer 
  namespace: galileo-seven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: latimer
  template:
    metadata:
      labels:
        app: latimer
    spec:
      containers:
      - name: nginx
        image: katacoda/docker-http-server:latest
#        image: registry.susealliances.com/docker-http-server:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: latimer-service
  namespace: galileo-seven
spec:
  type: NodePort
  selector:
    app: latimer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaetano
  namespace: galileo-seven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gaetano
  template:
    metadata:
      labels:
        app: gaetano
    spec:
      containers:
      - name: nginx
#        image: katacoda/docker-http-server:latest
        image: registry.susealliances.com/docker-http-server:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: gaetano-service
  namespace: galileo-seven
spec:
  type: NodePort
  selector:
    app: gaetano
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sles-deployment
  namespace: galileo-seven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sles-pod
  template:
    metadata:
      labels:
        app: sles-pod
    spec:
      containers:
        - name: sles-container
          image: registry.suse.com/bci/bci-base:latest
          command: ["bash"]
          stdin: true
          tty: true
---          
