apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: service
    enable: true
    mode: monitor
  rules:
  - action: deny
    criteria:
    - name: allowPrivEscalation
      op: =
      value: "true"
    - name: runAsPrivileged
      op: =
      value: "true"
    - name: runAsRoot
      op: =
      value: "true"
