apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: annotationSECCOMPRuntimeDefault
spec:
  config:
    client_mode: service
    enable: false
    mode: monitor
  rules:
  - action: deny
    comment: Block pods that do not enable SECCOMP runtime/default
    criteria:
    - name: customPath
      op: notContainsAny
      path: item.annotations.seccomp.security.alpha.kubernetes.io/pod
      type: customPath
      value: "runtime/default"
      value_type: string
    - name: ""
      op: notExist
      path: item.annotations.seccomp.security.alpha.kubernetes.io/pod
      type: customPath
      value: ""
      value_type: key
